_target_: src.datamodules.librispeech_datamodule.LibriSpeechDataModule

data_dir: ${data_dir_hd}librispeech/encoded # data_dir is specified in train.yaml or test.yaml #TODO is it really??
cache_dir: ${cache_dir}
train_batch_size: 32
val_batch_size: 64
test_batch_size: 64
load_preprocessed_data: True
train_split: train.360
pin_memory: True
debug: false

collator:
  _target_: src.datamodules.components.librispeech_dataset.LibriCollator
  load_preprocessed_data: True
  load_encoded_text: True
  pretrained_speech_model: ${model.model.pretrained_speech_model} # ntu-spml/distilhubert
  speech_max_length: 80000
  pretrained_text_model: ${model.model.pretrained_text_model} # google/bert_uncased_L-2_H-768_A-12
  text_max_length: 32