_target_: src.datamodules.librispeech_datamodule.LibriSpeechDataModule

data_dir: ${data_dir_hd}librispeech/original # data_dir is specified in train.yaml or test.yaml #TODO is it really??
cache_dir: ${data_dir_hd}librispeech/original
train_batch_size: 256
val_batch_size: 100
test_batch_size: 100
load_preprocessed_data: False
train_split: train.100
pin_memory: True
debug: False

collator:
  _target_: src.datamodules.components.librispeech_dataset.LibriCollator
  load_preprocessed_data: False
  load_encoded_text: False
  pretrained_speech_model: ${pretrained_speech_model}
  speech_max_length: 48000
  pretrained_text_model: ${pretrained_text_model}
  text_max_length: 32